steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/gcloud-app-backend:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/gcloud-app-backend:latest"
      - "."
    id: "build-image"

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/gcloud-app-backend:$COMMIT_SHA"
    id: "push-image"

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "gcloud-app-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/gcloud-app-backend:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
    id: "deploy-to-cloud-run"

images:
  - "gcr.io/$PROJECT_ID/gcloud-app-backend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/gcloud-app-backend:latest"

options:
  logging: CLOUD_LOGGING_ONLY
